/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNovosprojetosRouteImport } from './routes/_authenticated/novosprojetos'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes/index'
import { Route as AuthenticatedConfiguracoesSistemaRouteImport } from './routes/_authenticated/configuracoes/sistema'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes/usuarios'
import { Route as AuthenticatedCongregacoesIndexRouteImport } from './routes/_authenticated/congregacoes/index'
import { Route as AuthenticatedCongregacoesListaRouteImport } from './routes/_authenticated/congregacoes/lista'
import { Route as AuthenticatedCongregacoesPainelRouteImport } from './routes/_authenticated/congregacoes/painel'
import { Route as AuthenticatedEbdIndexRouteImport } from './routes/_authenticated/ebd/index'
import { Route as AuthenticatedEbdCadastrarAulasRouteImport } from './routes/_authenticated/ebd/cadastrar-aulas'
import { Route as AuthenticatedEbdPainelRouteImport } from './routes/_authenticated/ebd/painel'
import { Route as AuthenticatedEbdTurmasRouteImport } from './routes/_authenticated/ebd/turmas'
import { Route as AuthenticatedMembrosIndexRouteImport } from './routes/_authenticated/membros/index'
import { Route as AuthenticatedMembrosListaRouteImport } from './routes/_authenticated/membros/lista'
import { Route as AuthenticatedMembrosPainelRouteImport } from './routes/_authenticated/membros/painel'
import { Route as AuthenticatedPapoRetoIndexRouteImport } from './routes/_authenticated/papo-reto/index'
import { Route as AuthenticatedPapoRetoAgendarRouteImport } from './routes/_authenticated/papo-reto/agendar'
import { Route as AuthenticatedPapoRetoAprovacoesRouteImport } from './routes/_authenticated/papo-reto/aprovacoes'
import { Route as AuthenticatedPapoRetoCadastrarHorarioRouteImport } from './routes/_authenticated/papo-reto/cadastrar-horario'
import { Route as AuthenticatedPapoRetoMeusAgendamentosRouteImport } from './routes/_authenticated/papo-reto/meus-agendamentos'
import { Route as AuthenticatedPerfilIndexRouteImport } from './routes/_authenticated/perfil/index'
import { Route as AuthenticatedPerfilAcessosRouteImport } from './routes/_authenticated/perfil/acessos'
import { Route as AuthenticatedSuporteIndexRouteImport } from './routes/_authenticated/suporte/index'
import { Route as AuthenticatedSuporteAjudaRouteImport } from './routes/_authenticated/suporte/ajuda'
import { Route as AuthenticatedSuporteHistoricoRouteImport } from './routes/_authenticated/suporte/historico'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovosprojetosRoute =
  AuthenticatedNovosprojetosRouteImport.update({
    id: '/novosprojetos',
    path: '/novosprojetos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesSistemaRoute =
  AuthenticatedConfiguracoesSistemaRouteImport.update({
    id: '/configuracoes/sistema',
    path: '/configuracoes/sistema',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/configuracoes/usuarios',
    path: '/configuracoes/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCongregacoesIndexRoute =
  AuthenticatedCongregacoesIndexRouteImport.update({
    id: '/congregacoes/',
    path: '/congregacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCongregacoesListaRoute =
  AuthenticatedCongregacoesListaRouteImport.update({
    id: '/congregacoes/lista',
    path: '/congregacoes/lista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCongregacoesPainelRoute =
  AuthenticatedCongregacoesPainelRouteImport.update({
    id: '/congregacoes/painel',
    path: '/congregacoes/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEbdIndexRoute = AuthenticatedEbdIndexRouteImport.update({
  id: '/ebd/',
  path: '/ebd/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbdCadastrarAulasRoute =
  AuthenticatedEbdCadastrarAulasRouteImport.update({
    id: '/ebd/cadastrar-aulas',
    path: '/ebd/cadastrar-aulas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEbdPainelRoute = AuthenticatedEbdPainelRouteImport.update({
  id: '/ebd/painel',
  path: '/ebd/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbdTurmasRoute = AuthenticatedEbdTurmasRouteImport.update({
  id: '/ebd/turmas',
  path: '/ebd/turmas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembrosIndexRoute =
  AuthenticatedMembrosIndexRouteImport.update({
    id: '/membros/',
    path: '/membros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembrosListaRoute =
  AuthenticatedMembrosListaRouteImport.update({
    id: '/membros/lista',
    path: '/membros/lista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembrosPainelRoute =
  AuthenticatedMembrosPainelRouteImport.update({
    id: '/membros/painel',
    path: '/membros/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapoRetoIndexRoute =
  AuthenticatedPapoRetoIndexRouteImport.update({
    id: '/papo-reto/',
    path: '/papo-reto/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapoRetoAgendarRoute =
  AuthenticatedPapoRetoAgendarRouteImport.update({
    id: '/papo-reto/agendar',
    path: '/papo-reto/agendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapoRetoAprovacoesRoute =
  AuthenticatedPapoRetoAprovacoesRouteImport.update({
    id: '/papo-reto/aprovacoes',
    path: '/papo-reto/aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapoRetoCadastrarHorarioRoute =
  AuthenticatedPapoRetoCadastrarHorarioRouteImport.update({
    id: '/papo-reto/cadastrar-horario',
    path: '/papo-reto/cadastrar-horario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapoRetoMeusAgendamentosRoute =
  AuthenticatedPapoRetoMeusAgendamentosRouteImport.update({
    id: '/papo-reto/meus-agendamentos',
    path: '/papo-reto/meus-agendamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilIndexRoute =
  AuthenticatedPerfilIndexRouteImport.update({
    id: '/perfil/',
    path: '/perfil/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilAcessosRoute =
  AuthenticatedPerfilAcessosRouteImport.update({
    id: '/perfil/acessos',
    path: '/perfil/acessos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuporteIndexRoute =
  AuthenticatedSuporteIndexRouteImport.update({
    id: '/suporte/',
    path: '/suporte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuporteAjudaRoute =
  AuthenticatedSuporteAjudaRouteImport.update({
    id: '/suporte/ajuda',
    path: '/suporte/ajuda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuporteHistoricoRoute =
  AuthenticatedSuporteHistoricoRouteImport.update({
    id: '/suporte/historico',
    path: '/suporte/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/novosprojetos': typeof AuthenticatedNovosprojetosRoute
  '/configuracoes/sistema': typeof AuthenticatedConfiguracoesSistemaRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/congregacoes/lista': typeof AuthenticatedCongregacoesListaRoute
  '/congregacoes/painel': typeof AuthenticatedCongregacoesPainelRoute
  '/ebd/cadastrar-aulas': typeof AuthenticatedEbdCadastrarAulasRoute
  '/ebd/painel': typeof AuthenticatedEbdPainelRoute
  '/ebd/turmas': typeof AuthenticatedEbdTurmasRoute
  '/membros/lista': typeof AuthenticatedMembrosListaRoute
  '/membros/painel': typeof AuthenticatedMembrosPainelRoute
  '/papo-reto/agendar': typeof AuthenticatedPapoRetoAgendarRoute
  '/papo-reto/aprovacoes': typeof AuthenticatedPapoRetoAprovacoesRoute
  '/papo-reto/cadastrar-horario': typeof AuthenticatedPapoRetoCadastrarHorarioRoute
  '/papo-reto/meus-agendamentos': typeof AuthenticatedPapoRetoMeusAgendamentosRoute
  '/perfil/acessos': typeof AuthenticatedPerfilAcessosRoute
  '/suporte/ajuda': typeof AuthenticatedSuporteAjudaRoute
  '/suporte/historico': typeof AuthenticatedSuporteHistoricoRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/congregacoes/': typeof AuthenticatedCongregacoesIndexRoute
  '/ebd/': typeof AuthenticatedEbdIndexRoute
  '/membros/': typeof AuthenticatedMembrosIndexRoute
  '/papo-reto/': typeof AuthenticatedPapoRetoIndexRoute
  '/perfil/': typeof AuthenticatedPerfilIndexRoute
  '/suporte/': typeof AuthenticatedSuporteIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/novosprojetos': typeof AuthenticatedNovosprojetosRoute
  '/': typeof AuthenticatedIndexRoute
  '/configuracoes/sistema': typeof AuthenticatedConfiguracoesSistemaRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/congregacoes/lista': typeof AuthenticatedCongregacoesListaRoute
  '/congregacoes/painel': typeof AuthenticatedCongregacoesPainelRoute
  '/ebd/cadastrar-aulas': typeof AuthenticatedEbdCadastrarAulasRoute
  '/ebd/painel': typeof AuthenticatedEbdPainelRoute
  '/ebd/turmas': typeof AuthenticatedEbdTurmasRoute
  '/membros/lista': typeof AuthenticatedMembrosListaRoute
  '/membros/painel': typeof AuthenticatedMembrosPainelRoute
  '/papo-reto/agendar': typeof AuthenticatedPapoRetoAgendarRoute
  '/papo-reto/aprovacoes': typeof AuthenticatedPapoRetoAprovacoesRoute
  '/papo-reto/cadastrar-horario': typeof AuthenticatedPapoRetoCadastrarHorarioRoute
  '/papo-reto/meus-agendamentos': typeof AuthenticatedPapoRetoMeusAgendamentosRoute
  '/perfil/acessos': typeof AuthenticatedPerfilAcessosRoute
  '/suporte/ajuda': typeof AuthenticatedSuporteAjudaRoute
  '/suporte/historico': typeof AuthenticatedSuporteHistoricoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/congregacoes': typeof AuthenticatedCongregacoesIndexRoute
  '/ebd': typeof AuthenticatedEbdIndexRoute
  '/membros': typeof AuthenticatedMembrosIndexRoute
  '/papo-reto': typeof AuthenticatedPapoRetoIndexRoute
  '/perfil': typeof AuthenticatedPerfilIndexRoute
  '/suporte': typeof AuthenticatedSuporteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/novosprojetos': typeof AuthenticatedNovosprojetosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/configuracoes/sistema': typeof AuthenticatedConfiguracoesSistemaRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/congregacoes/lista': typeof AuthenticatedCongregacoesListaRoute
  '/_authenticated/congregacoes/painel': typeof AuthenticatedCongregacoesPainelRoute
  '/_authenticated/ebd/cadastrar-aulas': typeof AuthenticatedEbdCadastrarAulasRoute
  '/_authenticated/ebd/painel': typeof AuthenticatedEbdPainelRoute
  '/_authenticated/ebd/turmas': typeof AuthenticatedEbdTurmasRoute
  '/_authenticated/membros/lista': typeof AuthenticatedMembrosListaRoute
  '/_authenticated/membros/painel': typeof AuthenticatedMembrosPainelRoute
  '/_authenticated/papo-reto/agendar': typeof AuthenticatedPapoRetoAgendarRoute
  '/_authenticated/papo-reto/aprovacoes': typeof AuthenticatedPapoRetoAprovacoesRoute
  '/_authenticated/papo-reto/cadastrar-horario': typeof AuthenticatedPapoRetoCadastrarHorarioRoute
  '/_authenticated/papo-reto/meus-agendamentos': typeof AuthenticatedPapoRetoMeusAgendamentosRoute
  '/_authenticated/perfil/acessos': typeof AuthenticatedPerfilAcessosRoute
  '/_authenticated/suporte/ajuda': typeof AuthenticatedSuporteAjudaRoute
  '/_authenticated/suporte/historico': typeof AuthenticatedSuporteHistoricoRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/congregacoes/': typeof AuthenticatedCongregacoesIndexRoute
  '/_authenticated/ebd/': typeof AuthenticatedEbdIndexRoute
  '/_authenticated/membros/': typeof AuthenticatedMembrosIndexRoute
  '/_authenticated/papo-reto/': typeof AuthenticatedPapoRetoIndexRoute
  '/_authenticated/perfil/': typeof AuthenticatedPerfilIndexRoute
  '/_authenticated/suporte/': typeof AuthenticatedSuporteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arquivos'
    | '/calendario'
    | '/inicio'
    | '/novosprojetos'
    | '/configuracoes/sistema'
    | '/configuracoes/usuarios'
    | '/congregacoes/lista'
    | '/congregacoes/painel'
    | '/ebd/cadastrar-aulas'
    | '/ebd/painel'
    | '/ebd/turmas'
    | '/membros/lista'
    | '/membros/painel'
    | '/papo-reto/agendar'
    | '/papo-reto/aprovacoes'
    | '/papo-reto/cadastrar-horario'
    | '/papo-reto/meus-agendamentos'
    | '/perfil/acessos'
    | '/suporte/ajuda'
    | '/suporte/historico'
    | '/configuracoes/'
    | '/congregacoes/'
    | '/ebd/'
    | '/membros/'
    | '/papo-reto/'
    | '/perfil/'
    | '/suporte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/arquivos'
    | '/calendario'
    | '/inicio'
    | '/novosprojetos'
    | '/'
    | '/configuracoes/sistema'
    | '/configuracoes/usuarios'
    | '/congregacoes/lista'
    | '/congregacoes/painel'
    | '/ebd/cadastrar-aulas'
    | '/ebd/painel'
    | '/ebd/turmas'
    | '/membros/lista'
    | '/membros/painel'
    | '/papo-reto/agendar'
    | '/papo-reto/aprovacoes'
    | '/papo-reto/cadastrar-horario'
    | '/papo-reto/meus-agendamentos'
    | '/perfil/acessos'
    | '/suporte/ajuda'
    | '/suporte/historico'
    | '/configuracoes'
    | '/congregacoes'
    | '/ebd'
    | '/membros'
    | '/papo-reto'
    | '/perfil'
    | '/suporte'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arquivos'
    | '/_authenticated/calendario'
    | '/_authenticated/inicio'
    | '/_authenticated/novosprojetos'
    | '/_authenticated/'
    | '/_authenticated/configuracoes/sistema'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/congregacoes/lista'
    | '/_authenticated/congregacoes/painel'
    | '/_authenticated/ebd/cadastrar-aulas'
    | '/_authenticated/ebd/painel'
    | '/_authenticated/ebd/turmas'
    | '/_authenticated/membros/lista'
    | '/_authenticated/membros/painel'
    | '/_authenticated/papo-reto/agendar'
    | '/_authenticated/papo-reto/aprovacoes'
    | '/_authenticated/papo-reto/cadastrar-horario'
    | '/_authenticated/papo-reto/meus-agendamentos'
    | '/_authenticated/perfil/acessos'
    | '/_authenticated/suporte/ajuda'
    | '/_authenticated/suporte/historico'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/congregacoes/'
    | '/_authenticated/ebd/'
    | '/_authenticated/membros/'
    | '/_authenticated/papo-reto/'
    | '/_authenticated/perfil/'
    | '/_authenticated/suporte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novosprojetos': {
      id: '/_authenticated/novosprojetos'
      path: '/novosprojetos'
      fullPath: '/novosprojetos'
      preLoaderRoute: typeof AuthenticatedNovosprojetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/sistema': {
      id: '/_authenticated/configuracoes/sistema'
      path: '/configuracoes/sistema'
      fullPath: '/configuracoes/sistema'
      preLoaderRoute: typeof AuthenticatedConfiguracoesSistemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/configuracoes/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/congregacoes/': {
      id: '/_authenticated/congregacoes/'
      path: '/congregacoes'
      fullPath: '/congregacoes/'
      preLoaderRoute: typeof AuthenticatedCongregacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/congregacoes/lista': {
      id: '/_authenticated/congregacoes/lista'
      path: '/congregacoes/lista'
      fullPath: '/congregacoes/lista'
      preLoaderRoute: typeof AuthenticatedCongregacoesListaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/congregacoes/painel': {
      id: '/_authenticated/congregacoes/painel'
      path: '/congregacoes/painel'
      fullPath: '/congregacoes/painel'
      preLoaderRoute: typeof AuthenticatedCongregacoesPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebd/': {
      id: '/_authenticated/ebd/'
      path: '/ebd'
      fullPath: '/ebd/'
      preLoaderRoute: typeof AuthenticatedEbdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebd/cadastrar-aulas': {
      id: '/_authenticated/ebd/cadastrar-aulas'
      path: '/ebd/cadastrar-aulas'
      fullPath: '/ebd/cadastrar-aulas'
      preLoaderRoute: typeof AuthenticatedEbdCadastrarAulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebd/painel': {
      id: '/_authenticated/ebd/painel'
      path: '/ebd/painel'
      fullPath: '/ebd/painel'
      preLoaderRoute: typeof AuthenticatedEbdPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebd/turmas': {
      id: '/_authenticated/ebd/turmas'
      path: '/ebd/turmas'
      fullPath: '/ebd/turmas'
      preLoaderRoute: typeof AuthenticatedEbdTurmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros/': {
      id: '/_authenticated/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof AuthenticatedMembrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros/lista': {
      id: '/_authenticated/membros/lista'
      path: '/membros/lista'
      fullPath: '/membros/lista'
      preLoaderRoute: typeof AuthenticatedMembrosListaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros/painel': {
      id: '/_authenticated/membros/painel'
      path: '/membros/painel'
      fullPath: '/membros/painel'
      preLoaderRoute: typeof AuthenticatedMembrosPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papo-reto/': {
      id: '/_authenticated/papo-reto/'
      path: '/papo-reto'
      fullPath: '/papo-reto/'
      preLoaderRoute: typeof AuthenticatedPapoRetoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papo-reto/agendar': {
      id: '/_authenticated/papo-reto/agendar'
      path: '/papo-reto/agendar'
      fullPath: '/papo-reto/agendar'
      preLoaderRoute: typeof AuthenticatedPapoRetoAgendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papo-reto/aprovacoes': {
      id: '/_authenticated/papo-reto/aprovacoes'
      path: '/papo-reto/aprovacoes'
      fullPath: '/papo-reto/aprovacoes'
      preLoaderRoute: typeof AuthenticatedPapoRetoAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papo-reto/cadastrar-horario': {
      id: '/_authenticated/papo-reto/cadastrar-horario'
      path: '/papo-reto/cadastrar-horario'
      fullPath: '/papo-reto/cadastrar-horario'
      preLoaderRoute: typeof AuthenticatedPapoRetoCadastrarHorarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papo-reto/meus-agendamentos': {
      id: '/_authenticated/papo-reto/meus-agendamentos'
      path: '/papo-reto/meus-agendamentos'
      fullPath: '/papo-reto/meus-agendamentos'
      preLoaderRoute: typeof AuthenticatedPapoRetoMeusAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/': {
      id: '/_authenticated/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AuthenticatedPerfilIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/acessos': {
      id: '/_authenticated/perfil/acessos'
      path: '/perfil/acessos'
      fullPath: '/perfil/acessos'
      preLoaderRoute: typeof AuthenticatedPerfilAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte/': {
      id: '/_authenticated/suporte/'
      path: '/suporte'
      fullPath: '/suporte/'
      preLoaderRoute: typeof AuthenticatedSuporteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte/ajuda': {
      id: '/_authenticated/suporte/ajuda'
      path: '/suporte/ajuda'
      fullPath: '/suporte/ajuda'
      preLoaderRoute: typeof AuthenticatedSuporteAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte/historico': {
      id: '/_authenticated/suporte/historico'
      path: '/suporte/historico'
      fullPath: '/suporte/historico'
      preLoaderRoute: typeof AuthenticatedSuporteHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNovosprojetosRoute: typeof AuthenticatedNovosprojetosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConfiguracoesSistemaRoute: typeof AuthenticatedConfiguracoesSistemaRoute
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
  AuthenticatedCongregacoesListaRoute: typeof AuthenticatedCongregacoesListaRoute
  AuthenticatedCongregacoesPainelRoute: typeof AuthenticatedCongregacoesPainelRoute
  AuthenticatedEbdCadastrarAulasRoute: typeof AuthenticatedEbdCadastrarAulasRoute
  AuthenticatedEbdPainelRoute: typeof AuthenticatedEbdPainelRoute
  AuthenticatedEbdTurmasRoute: typeof AuthenticatedEbdTurmasRoute
  AuthenticatedMembrosListaRoute: typeof AuthenticatedMembrosListaRoute
  AuthenticatedMembrosPainelRoute: typeof AuthenticatedMembrosPainelRoute
  AuthenticatedPapoRetoAgendarRoute: typeof AuthenticatedPapoRetoAgendarRoute
  AuthenticatedPapoRetoAprovacoesRoute: typeof AuthenticatedPapoRetoAprovacoesRoute
  AuthenticatedPapoRetoCadastrarHorarioRoute: typeof AuthenticatedPapoRetoCadastrarHorarioRoute
  AuthenticatedPapoRetoMeusAgendamentosRoute: typeof AuthenticatedPapoRetoMeusAgendamentosRoute
  AuthenticatedPerfilAcessosRoute: typeof AuthenticatedPerfilAcessosRoute
  AuthenticatedSuporteAjudaRoute: typeof AuthenticatedSuporteAjudaRoute
  AuthenticatedSuporteHistoricoRoute: typeof AuthenticatedSuporteHistoricoRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
  AuthenticatedCongregacoesIndexRoute: typeof AuthenticatedCongregacoesIndexRoute
  AuthenticatedEbdIndexRoute: typeof AuthenticatedEbdIndexRoute
  AuthenticatedMembrosIndexRoute: typeof AuthenticatedMembrosIndexRoute
  AuthenticatedPapoRetoIndexRoute: typeof AuthenticatedPapoRetoIndexRoute
  AuthenticatedPerfilIndexRoute: typeof AuthenticatedPerfilIndexRoute
  AuthenticatedSuporteIndexRoute: typeof AuthenticatedSuporteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNovosprojetosRoute: AuthenticatedNovosprojetosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConfiguracoesSistemaRoute:
    AuthenticatedConfiguracoesSistemaRoute,
  AuthenticatedConfiguracoesUsuariosRoute:
    AuthenticatedConfiguracoesUsuariosRoute,
  AuthenticatedCongregacoesListaRoute: AuthenticatedCongregacoesListaRoute,
  AuthenticatedCongregacoesPainelRoute: AuthenticatedCongregacoesPainelRoute,
  AuthenticatedEbdCadastrarAulasRoute: AuthenticatedEbdCadastrarAulasRoute,
  AuthenticatedEbdPainelRoute: AuthenticatedEbdPainelRoute,
  AuthenticatedEbdTurmasRoute: AuthenticatedEbdTurmasRoute,
  AuthenticatedMembrosListaRoute: AuthenticatedMembrosListaRoute,
  AuthenticatedMembrosPainelRoute: AuthenticatedMembrosPainelRoute,
  AuthenticatedPapoRetoAgendarRoute: AuthenticatedPapoRetoAgendarRoute,
  AuthenticatedPapoRetoAprovacoesRoute: AuthenticatedPapoRetoAprovacoesRoute,
  AuthenticatedPapoRetoCadastrarHorarioRoute:
    AuthenticatedPapoRetoCadastrarHorarioRoute,
  AuthenticatedPapoRetoMeusAgendamentosRoute:
    AuthenticatedPapoRetoMeusAgendamentosRoute,
  AuthenticatedPerfilAcessosRoute: AuthenticatedPerfilAcessosRoute,
  AuthenticatedSuporteAjudaRoute: AuthenticatedSuporteAjudaRoute,
  AuthenticatedSuporteHistoricoRoute: AuthenticatedSuporteHistoricoRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  AuthenticatedCongregacoesIndexRoute: AuthenticatedCongregacoesIndexRoute,
  AuthenticatedEbdIndexRoute: AuthenticatedEbdIndexRoute,
  AuthenticatedMembrosIndexRoute: AuthenticatedMembrosIndexRoute,
  AuthenticatedPapoRetoIndexRoute: AuthenticatedPapoRetoIndexRoute,
  AuthenticatedPerfilIndexRoute: AuthenticatedPerfilIndexRoute,
  AuthenticatedSuporteIndexRoute: AuthenticatedSuporteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
